export const TEXT = {
    OK: 'OK'
}

export const ROLES = {
    ADMIN: "ADMIN",
    EMPLOYEE: "EMPLOYEE"
}

export const PERMISSIONS = {
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    CREATE_CUSTOMER: 'CREATE_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    UPDATE_BUSINESS: 'UPDATE_BUSINESS',
    CREATE_PLAN: 'CREATE_PLAN',
    UPDATE_PLAN: 'UPDATE_PLAN',
    DELETE_PLAN: 'DELETE_PLAN',
    CREATE_CUSTOMER_PLAN: 'CREATE_CUSTOMER_PLAN',
    CREATE_BUSINESS_PLAN: 'CREATE_BUSINESS_PLAN'
}

export const ALLOWED_ORIGINS = [
  'http://localhost:3000',
  'https://gms-theta.vercel.app'
]